name: e_commerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  bloc: ^9.0.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700

  uses-material-design: true
